### ISSUE TITLE
Enabling cgroups through /boot/firmware/cmdline.txt fails on x86_64 ubuntu server 20.04

### ISSUE THREAD

**Issue by insanitywholesale** [rancher/k3s-ansible#70] opened 2020-07-27 14:11 UTC
When trying to enable cgroups, the playbook tries to do it through the `/boot/firmware/cmdline.txt` file which doesn't exist since that's not where the kernel cmdline arguments are defined on the latest ubuntu server version on x86_64.
This resulting output is
```
fatal: [k3s-main]: FAILED! => {"changed": false, "msg": "Destination /boot/firmware/cmdline.txt does not exist !", "rc": 257}
```
I think this step should be skipped on non-RPi machines and refactored for the rest of the cases either through a templated `/etc/default/grub` file that will be distro and architecture specific or by checking the kernel config in `/boot/` like below
```
grep CONFIG_CGROUPS= /boot/config-`uname -r`
```
which if successful returns
```
CONFIG_CGROUPS=y
```

**Comment by fnord123** [comment] 2020-07-27 14:39
This is a duplicate of #40 and #49.  Pull request #54 fixes this, just needs to be merged.

**Comment by St0rmingBr4in** [comment] 2020-07-30 14:37
I merged @fnord123 PR, closing.

**Closed by St0rmingBr4in** 2020-07-30 14:37 UTC
