### ISSUE TITLE
Add role/meta to enable ansible-galaxy installs

### ISSUE THREAD

**Issue by andersliland** [rancher/k3s-ansible#35] opened 2020-05-23 18:34 UTC
Add role metadata to enable

ansible-galaxy install -r requirements.yaml

# Content of requirements.yaml

- name: prereq
   src: https://github.com/rancher/k3s-ansible
   path: roles/prereq

**Comment by geerlingguy** [comment] 2020-05-29 17:35
@andersliland - I think the idea of sharing the roles on Galaxy is worthy, but would require a bit of an architecture shift, as the roles are currently constructed in a way that ties them strongly to this k3s-ansible playbook.

I'm not sure if that's desireable or not, as making them more generic could add a little more complexity to this project. But it would potentially broaden the reach and scope.

**Comment by itwars** [comment] 2020-06-05 08:15
Duplicate of #39

**Closed by itwars** 2020-06-05 08:15 UTC

**Comment by paulfantom** [comment] 2020-06-05 08:17
I did this refactor with the aim to put it in ansible-galaxy in https://github.com/rancher/k3s/pull/1649, but don't have time right now to get back to that.

Those refactored roles are currently used by me in https://github.com/thaum-xyz/ankhmorpork/tree/master/ansible
